### ISSUE TITLE
Implement Event Streaming

### ISSUE THREAD

**Issue by Lachstec** [srieger1/digsinet#19]
The current version uses basic python message queues as exchange medium between siblings. Although it was convenient for the proof of concept, a more robust event streaming platform would be valuable. 

### TODO
- [x] Add a common Interface for Event / Message Brokers
- [x] Add Settings for Kafka configuration
- [x] Add Settings for RabbitMQ configuration
- [x] Implement a client for using Rabbit MQ as a Event / Message Broker
- [x] Implement a client for using Kafka as a Event / Message Broker
- [x] Update digsinet to use an instance of the interface
- [x] Testing if Kafka works
- [x] Testing if RabbitMQ works

**Comment by S-Schickentanz** [comment]
Interface Design:

- init(config, channels: str, logger)
- publish(channel: str, value),
- poll(channel: str, timeout),
- subscribe(channel: str),
- get_sibling_channels(),
- new_sibling_channel(channel: str),
- close()

**Comment by Lachstec** [comment]
I made a branch and added the interface as described here. Feel free to make changes to it as you see fit.

**Comment by Lachstec** [comment]
It could be useful to factor out the sibling creation into a separate module / class / whatever. The creation would get a bit more specific to the underlying message broker and it could get messy if that is implemented in the main file.

**Comment by srieger1** [comment]
@Lachstec good point... that's somehow what I meant when I said, that it might be interesting to have both, a message queue (like Rabbit) for tasks (e.g., creation and control of siblings) and an event-streaming (like Kafka) for state updates and synchronization. However, this increases complexity and maybe we don't want/need that.

**Comment by Lachstec** [comment]
Event-Streaming for Kafka is working right now, although there were some weird bugs. They have been documented in the issues #24 #23 accordingly.
