### ISSUE TITLE
Refactor configuration management 

### ISSUE THREAD

**Issue by Lachstec** [srieger1/digsinet#20]
Currently, the configuration is passed in via a big yaml file that gets parsed into a dictionary. This is a bit inconvienient as it neither documents what configuration values are available and it pollutes the main function. Maybe it would be nice to refactor it out into a separate class?

**Comment by Lachstec** [comment]
Currently working on this and making progress.

### TODO
- [X] Write a config parser as seperate class
- [ ] Change main to use the new parser
- [ ] Adapt methods to the new config class where needed
