### ISSUE TITLE
Implement Fuzzing with AFLnet in the security sibling

### ISSUE THREAD

**Issue by Lachstec** [srieger1/digsinet#7]
# Highlevel Idea
One primary usecase for the security sibling is fuzz testing of the network services that are running on e.g. the network components in the physical network in order to discover security issues / bugs.

## Concept
The desired functionality could be implemented by creating one or more containers in a clab instance that run aflnet against the containers running. For the initial version, it should be sufficient to limit the duration for which the fuzzer runs and then emplacing the results in the message queue for further processing.

## TODO
- [ ] Inject aflnet as Container into clab 
- [ ] Let aflnet terminate after a set timeout
- [ ] Report results back to digsinet via queue

**Comment by Lachstec** [comment]
Closing as Event Streaming is the primary focus for now
